//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETO
    {
        public string ID_OBJETO { get; set; }
        public string NOMBRE { get; set; }
        public int CANTIDAD { get; set; }
        public Nullable<int> PRECIO { get; set; }
        public string MARCA { get; set; }
    }
}
